# Generated by Django 5.1.6 on 2025-04-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyRenewal',
            fields=[
                ('renewal_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('renewal_warranty_start', models.DateField(blank=True, null=True)),
                ('renewal_warranty_end', models.DateField(blank=True, null=True)),
                ('renewal_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': '"services"."warranty_renewal"',
                'managed': False,
            },
        ),
    ]
