# Generated by Django 5.1.6 on 2025-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCall',
            fields=[
                ('service_call_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('call_type', models.CharField(choices=[('Inquiry', 'Inquiry'), ('Request', 'Request'), ('Other', 'Other')], default='Inquiry', max_length=20)),
                ('call_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('In Progress', 'In Progress')], default='Open', max_length=20)),
                ('date_closed', models.DateTimeField(null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"services"."service_call"',
                'managed': False,
            },
        ),
    ]
