# Generated by Django 5.1.6 on 2025-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('contract_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('contract_description', models.TextField(blank=True, null=True)),
                ('date_issued', models.DateField()),
                ('end_date', models.DateField()),
                ('contract_status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Expired', 'Expired'), ('Terminated', 'Terminated')], default='Pending', max_length=20)),
                ('renewal_bool', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '"services"."service_contract"',
                'managed': False,
            },
        ),
    ]
