# Generated by Django 5.1.6 on 2025-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAnalysis',
            fields=[
                ('analysis_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('analysis_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Done', 'Done')], default='Scheduled', max_length=20)),
                ('analysis_description', models.TextField(blank=True, null=True)),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': '"services"."service_analysis"',
                'managed': False,
            },
        ),
    ]
