# Generated by Django 5.1.6 on 2025-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('service_order_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': '"services"."service_order"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderItem',
            fields=[
                ('service_order_item_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('item_quantity', models.IntegerField(default=1)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': '"services"."service_order_item"',
                'managed': False,
            },
        ),
    ]
