# Generated by Django 5.1.6 on 2025-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('service_request_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('request_type', models.CharField(choices=[('Repair', 'Repair'), ('Installation', 'Installation'), ('Maintenance', 'Maintenance'), ('Renewal', 'Renewal'), ('Other', 'Other')], max_length=50)),
                ('request_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress')], max_length=50)),
                ('request_description', models.TextField(blank=True, null=True)),
                ('request_remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"services"."service_request"',
                'managed': False,
            },
        ),
    ]
