# Generated by Django 5.1.6 on 2025-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('delivery_order_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('delivery_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': '"services"."delivery_order"',
                'managed': False,
            },
        ),
    ]
