# Generated by Django 5.1.6 on 2025-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBilling',
            fields=[
                ('service_billing_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_billing_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('outsource_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('billing_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
                ('date_paid', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"services"."service_billing"',
                'managed': False,
            },
        ),
    ]
