# Generated by Django 5.1.6 on 2025-03-28 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddsService',
            fields=[
                ('additional_service_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': '"services"."additional_service"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddsServiceType',
            fields=[
                ('additional_service_type_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('service_type', models.TextField()),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(default=1)),
                ('date_start', models.DateField(auto_now=True)),
                ('status', models.TextField()),
                ('total_service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': '"services"."additional_service_type"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"sales"."customers"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': '"human_resources"."departments"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.TextField()),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': '"human_resources"."employees"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryItemMD',
            fields=[
                ('item_md_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('available_stock', models.IntegerField()),
            ],
            options={
                'db_table': '"inventory"."inventory_item_master_data"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemMasterData',
            fields=[
                ('item_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('item_type', models.TextField()),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"admin"."item_master_data"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpCost',
            fields=[
                ('operational_cost_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('total_operational_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': '"distribution"."operational_cost"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.TextField()),
                ('order_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_type', models.TextField()),
            ],
            options={
                'db_table': '"sales"."orders"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('policy_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.TextField()),
            ],
            options={
                'db_table': '"admin"."policies"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrincipalItem',
            fields=[
                ('principal_item_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('markup_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': '"mrp"."principal_items"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_level', models.IntegerField(blank=True, null=True)),
                ('warranty_period', models.IntegerField(blank=True, default=12, null=True)),
            ],
            options={
                'db_table': '"admin"."products"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RenewalWarranty',
            fields=[
                ('renewal_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('renewal_warranty_start', models.DateField(blank=True, null=True)),
                ('renewal_warranty_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"sales"."renewal_warranty"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('statement_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('type', models.TextField()),
                ('total_tax', models.IntegerField(default=0)),
            ],
            options={
                'db_table': '"sales"."statement"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatementItem',
            fields=[
                ('statement_item_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'db_table': '"sales"."statement_item"',
                'managed': False,
            },
        ),
    ]
