# Generated by Django 5.1.6 on 2025-04-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RenewalWarranty',
        ),
    ]
