# Generated by Django 5.1.6 on 2025-04-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_delete_renewalwarranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesPermission',
            fields=[
                ('role_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.TextField(blank=True, null=True)),
                ('access_level', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"admin"."roles_permission"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('status', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"admin"."users"',
                'managed': False,
            },
        ),
    ]
