# Generated by Django 5.1.6 on 2025-04-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_rolespermission_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('position_title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"human_resources"."positions"',
                'managed': False,
            },
        ),
    ]
