# Generated by Django 5.1.6 on 2025-04-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0004_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDocumentItem',
            fields=[
                ('productdocu_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"operations"."product_document_items"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('material_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': '"admin"."raw_materials"',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='inventoryitemmd',
            table='"inventory"."inventory_item"',
        ),
    ]
