# Generated by Django 5.1.6 on 2025-05-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0005_productdocumentitem_rawmaterial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('warehouse_location', models.CharField(blank=True, max_length=255, null=True)),
                ('warehouse_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '"admin"."warehouse"',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Policies',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductDocumentItem',
        ),
        migrations.DeleteModel(
            name='RawMaterial',
        ),
    ]
