# Generated by Django 5.1.6 on 2025-05-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0006_warehouse_delete_policies_delete_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('pricing_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('item_price', models.FloatField()),
            ],
            options={
                'db_table': '"mrp"."pricing"',
                'managed': False,
            },
        ),
    ]
