# Generated by Django 5.1.6 on 2025-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('report_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('request_type', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('report_status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Reviewed', 'Reviewed')], default='Draft', max_length=20)),
                ('submission_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': '"services"."service_report"',
                'managed': False,
            },
        ),
    ]
