# Generated by Django 5.1.6 on 2025-03-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfterAnalysis',
            fields=[
                ('analysis_sched_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('service_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('service_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('In Progress', 'In Progress')], default='Scheduled', max_length=20)),
            ],
            options={
                'db_table': '"services"."after_analysis_sched"',
                'managed': False,
            },
        ),
    ]
